(**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *)

unit Enums;

interface

uses
  Classes,
  SysUtils,
  Generics.Collections,
  Thrift,
  Thrift.Utils,
  Thrift.Collections,
  Thrift.Protocol,
  Thrift.Transport;

const
  cEnums_Option_AnsiStr_Binary = False;
type

{$SCOPEDENUMS ON}

  TPersonState = (
    UNVERIFIED = 0,
    VERIFIED = 1,
    GOLD = 2
  );

{$SCOPEDENUMS OFF}

implementation

end.
